# Generated by Django 4.1.2 on 2022-11-04 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("mysite", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("type", models.SmallIntegerField()),
                ("path", models.CharField(max_length=255)),
                ("size", models.IntegerField()),
                ("format", models.CharField(max_length=64)),
                ("limit", models.SmallIntegerField()),
            ],
            options={
                "db_table": "dataset",
            },
        ),
        migrations.CreateModel(
            name="StandModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("params", models.CharField(max_length=255)),
                ("train_path", models.CharField(blank=True, max_length=255, null=True)),
                ("net_path", models.CharField(max_length=255)),
                ("type", models.IntegerField()),
                ("info", models.CharField(blank=True, max_length=255, null=True)),
                ("dataset", models.ManyToManyField(to="mysite.dataset")),
            ],
            options={
                "db_table": "standmodel",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account", models.CharField(max_length=64, unique=True)),
                ("pwd", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("type", models.SmallIntegerField()),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="StandModelWeight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("weight_path", models.CharField(max_length=1000)),
                (
                    "standModel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysite.standmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mysite.user"
                    ),
                ),
            ],
            options={
                "db_table": "standmodelmap",
            },
        ),
        migrations.AddField(
            model_name="standmodel",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mysite.user"
            ),
        ),
        migrations.CreateModel(
            name="Model",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("status", models.SmallIntegerField()),
                ("process", models.BigIntegerField(blank=True, null=True)),
                ("weight", models.CharField(blank=True, max_length=255, null=True)),
                ("limit", models.SmallIntegerField(blank=True, null=True)),
                ("params", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "dataSet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mysite.dataset"
                    ),
                ),
                (
                    "standModel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mysite.standmodel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mysite.user"
                    ),
                ),
            ],
            options={
                "db_table": "model",
            },
        ),
        migrations.AddField(
            model_name="dataset",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mysite.user"
            ),
        ),
    ]
