# Generated by Django 4.1.2 on 2022-11-04 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="standmodelweight",
            table="standmodelweight",
        ),
    ]
