# Generated by Django 4.1.2 on 2022-11-15 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0005_standdataset_remove_standmodel_dataset_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="standdataset",
            table="stand_dataset",
        ),
    ]
