# Generated by Django 4.1.2 on 2022-11-15 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0008_dataset_label_num_dataset_total_num_dataset_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="standmodel",
            name="train_path",
        ),
    ]
