# Generated by Django 4.1.2 on 2022-11-16 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0012_alter_model_dataset"),
    ]

    operations = [
        migrations.AlterField(
            model_name="model",
            name="params",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
