# Generated by Django 4.1.2 on 2022-11-22 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mysite", "0013_alter_model_params"),
    ]

    operations = [
        migrations.AlterField(
            model_name="standmodel",
            name="params",
            field=models.CharField(max_length=2000),
        ),
    ]
